import type { Metadata } from 'next'
import { Inter, Jura } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'

const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-inter'
})

const jura = Jura({
  subsets: ['latin'],
  weight: '500',
  variable: '--font-jura'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${jura.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
